# This is a basic workflow to help you get started with Actions

name: Rebuild SQL Files

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out source code
        with:
          fetch-depth: 0
        uses: actions/checkout@v2
      
      - name: Set Git Config
        run: |
          #date >> ./_src/_build/generated.txt
          git config user.name github-actions-Rebuild
          git config user.email github-actions@github.com

      # Rebuild Files with Powershell script
      - name: Rebuild files
        shell: pwsh
        run: |
          ./_src/_build/rebuild-sql-files.ps1 ./_src/_build/orchestrator-db-maintenance.json  #, ./_src/_build/orchestrator-db-diagnostic.json

      #Commit Changes (if SUCCESS)
      - name: Commit
        if: ${{ success() }}
        shell: pwsh
        run: |
          try {
            git status
            git add .
            $main_commitdate=$(git log -1 --date=iso-strict --pretty=format:"%cd")
            $message=$(git log -1 --date=iso-strict --pretty='format:Rebuild after Commit %C(auto)%h (%s, %ad)')
            git diff-index --quiet HEAD || git commit --message="$($message)"
          }
          catch{
          }
      #Push Changes (if SUCCESS)
      - name: Push
        if: ${{ success() }}
        shell: pwsh
        run: |
          git push

